name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207   
    - name: clean
      run: dotnet clean -c Release
    - name: build
      run: dotnet build
    - name: test
      run: |
        dotnet tool install -g coverlet.console
        dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../opencover.xml ./Cashwu.AspNetCore.Configuration.Tests/Cashwu.AspNetCore.Configuration.Tests.csproj
    - name: upload coverage to codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: opencover.xml
        flags: unittests
        name: Cashwu.Core.Utility
    - name: dotnet pack
      run: dotnet pack ./Cashwu.AspNetCore.Configuration/Cashwu.AspNetCore.Configuration.csproj -c Release -o ../release
    - name: nuget publish
      if: github.ref == 'refs/heads/master'
      continue-on-error: true
      run: |
        dotnet nuget push ./release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
